print("Lua Tests")

local libmem = require("libmem_lua")
print("libmem_lua loaded")

target_proc = libmem.LM_FindProcess("target")
print("[*] Target Process")
print("PID: " .. target_proc.pid)
print("PPID: " .. target_proc.ppid)
print("Bits: " .. target_proc.bits)
print("Start Time: " .. target_proc.start_time)
print("Path: " .. target_proc.path)
print("Name: " .. target_proc.name)
print("(invalid): " .. (target_proc.invalid or "nil"))
print(target_proc)
