from libmem import *

pid = LM_GetProcessIdEx("test1")
ppid = LM_GetParentIdEx(pid)
proc = LM_OpenProcessEx(pid)
procpath = LM_GetProcessPathEx(proc)
procname = LM_GetProcessNameEx(proc)
procbits = LM_GetProcessBitsEx(proc)
sysbits = LM_GetSystemBits()
print(f"[*] PID: {proc.pid}")
print(f"[*] PPID: {int(ppid)}")
print(f"[*] Process Path: {procpath}")
print(f"[*] Process Name: {procname}")
print(f"[*] Process Bits: {procbits}")
print(f"[*] System Bits: {sysbits}")
LM_CloseProcess(proc)
